### ISSUE TITLE
support for beats 5.0.0 ?

### ISSUE THREAD

**Issue by cure** [christiangalsterer/httpbeat#10]
Beats 5.0.0 has been released; it looks like httpbeat needs some work to build against it:

<pre>
$ make
go build
# _/usr/src/httpbeat
./main.go:13: cannot use beater.New (type func(*"github.com/christiangalsterer/httpbeat/vendor/github.com/elastic/beats/libbeat/beat".Beat, *"github.com/christiangalsterer/httpbeat/vendor/github.com/elastic/beats/libbeat/common".Config) ("github.com/christiangalsterer/httpbeat/vendor/github.com/elastic/beats/libbeat/beat".Beater, error)) as type "github.com/elastic/beats/libbeat/beat".Creator in argument to "github.com/elastic/beats/libbeat/beat".Run
vendor/github.com/elastic/beats/libbeat/scripts/Makefile:73: recipe for target 'httpbeat' failed
make: *** [httpbeat] Error 2
</pre>

Any chance we can get an updated httpbeat for beats 5.0.0 ?

**Comment by christiangalsterer** [comment]
I'm already working on it and it and code wise I'm close to be ready, mainly documentation needs to be updated.

**Comment by christiangalsterer** [comment]
Just pushed the code changes and all local tests are green, next/last step is documentation. So if you have some time feel free to give it a try.

**Comment by cure** [comment]
awesome! It's still giving me the same build error, even after a make clean. Is Go 1.7 not supported yet?

**Comment by christiangalsterer** [comment]
I build with Go 1.7.1 and [Travis](https://travis-ci.org/christiangalsterer/httpbeat) is also happy.

Could it be that for some reason the vendor directory is not used and somewhere on older version of beat in the path which is used?

**Comment by ruflin** [comment]
@christiangalsterer I quickly tested the version on master and all looks good on my side.
@cure Did you pull the most recent version from Github?

**Comment by cure** [comment]
Confirmed, it builds and works for me. The problem was that I hadn't checked out the tree under GOPATH as listed in README.md (though there's a missing src/ in the path listed there).

**Comment by christiangalsterer** [comment]
Fixed the problem with missing the 'src' in the README.md

**Comment by christiangalsterer** [comment]
2.0.0 just released with support for beats 5.0.1

**Comment by Khezen** [comment]
Thank you very much
