### ISSUE TITLE
Elasticsearch plugin issue, missing json file

### ISSUE THREAD

**Issue by sahilravinder** [christiangalsterer/httpbeat#13]
Trying to launch httpbeat with elasticsearch plugin as the output, facing an issue -
 - Ran the XPUT template command first to create index in elasticsearch - success
-  Modified Httpbeat.yml file to send output to elasticsearch
-  Start Httpbeat with the command below
   ./httpbeat -c httpbeat.yml -e -d "*"
Error msg - 
ERR failed to initialize elasticsearch plugin as output: Error loading template /usr/local/go/src/github.com/christiangalsterer/httpbeat/httpbeat.template-es2x.json: open /usr/local/go/src/github.com/christiangalsterer/httpbeat/httpbeat.template-es2x.json: no such file or directory

**Comment by christiangalsterer** [comment]
Is the file available at the specified location?

**Comment by sahilravinder** [comment]
No, the file isn't available in this repository. Is there a mock template i can use to create this file ?

**Comment by rompic** [comment]
see https://github.com/christiangalsterer/httpbeat/blob/master/etc/httpbeat.yml and docs in https://github.com/christiangalsterer/httpbeat/blob/master/docs/configuration.asciidoc

**Comment by rompic** [comment]
ah sorry I misunderstood your request. you were looking for a template for httpbeat.template-es2x.json :|

**Comment by christiangalsterer** [comment]
Hi,
just pushed a change to master adding the missing file and also some cleanup in the existing httpbeat-template.json file.
I didn't had a change to test it, but would be great if you can give it a try.

**Comment by christiangalsterer** [comment]
Released with version 3.0.0
