### ISSUE TITLE
http beat consume > 2Gb of memory

### ISSUE THREAD

**Issue by istrakhouski** [christiangalsterer/httpbeat#17]
When there is no load on machine with httb beat every thing is ok, when we run load test, httpbeat begin consume more resources than our application. What is the reason if it still just should pull links and send responses to logstash?

Consumed memory:
![httpbeat-high-memory-consumtion](https://cloud.githubusercontent.com/assets/26307388/23762136/b560f650-04ba-11e7-86bc-d54ea708bac3.png)

Configuration:
` 
  urls:
    # Each - URL endpoints to call. Below are the URL endpoint specific configurations
#Url to monitor
      -
        url: http://localhost:80/service1/metrics
        method: get
        cron: '@every 15s'
        # Optional additional headers to send to the endpoint
        headers:
          Accept: application/json
        output_format: json
        json_dot_mode: replace
#Url to monitor
      -
        url: http://localhost:80/service2/metrics
        method: get
        cron: '@every 15s'
        # Optional additional headers to send to the endpoint
        headers:
          Accept: application/json
        output_format: json
        json_dot_mode: replace
#Url to monitor
      -
        url: http://localhost:80/service3/metrics
        method: get
        cron: '@every 15s'
        # Optional additional headers to send to the endpoint
        headers:
          Accept: application/json
        output_format: json
        json_dot_mode: replace
#Url to monitor
      -
        url: http://localhost:80/service4/metrics
        method: get
        cron: '@every 15s'
        # Optional additional headers to send to the endpoint
        headers:
          Accept: application/json
        output_format: json
        json_dot_mode: replace

`

**Comment by christiangalsterer** [comment]
I haven't seen this yet. Which version of the plugin to you use and which OS?

**Comment by alex-borkun** [comment]
The problem is reproduced on 4.0.0 version.

**Comment by christiangalsterer** [comment]
I tried to reproduce it and under OSX I was not able to reproduce it. Will try to test in the next days in a linux machine

**Comment by christiangalsterer** [comment]
I finally made now a very simple first test with a new version on Ubuntu and didn't encounter the issue. Will do some more tests.

Did you saw any differences with the new number of http endpoints you query and/or the frequency?

**Comment by istrakhouski** [comment]
Actually we wasn't able to reproduce it, we saw it couple of times, but didn't catch how and when it happens.
