### ISSUE TITLE
Is it possible to include response time?

### ISSUE THREAD

**Issue by brunodomenici** [christiangalsterer/httpbeat#21]
Hi,

Is it possible to include the response/transaction time?

Thanks

**Comment by christiangalsterer** [comment]
In general I think it is. With version 6.0 of Beats, Httpbeat will be part become a core module of Metricbeat (Http module) and Metricbeat has the common field [metric.rtt](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-common.html#_metricset_rtt).

So not sure if will still add it, as Httpbeat will get superseded by the Http module of Metricbeat,
