### ISSUE TITLE
Is it possible to set up a `config_dir` for conf files

### ISSUE THREAD

**Issue by aboullaite** [christiangalsterer/httpbeat#28]
Hi,
This is more of a question ;)! Just wondering if there is something equivalent to  `config_dir` in filebeat where we can put additional configuration files. I think it's useful when we've multiple hosts to monitor, it would be nice to save the conf of each host in its own file.

Thank you

**Comment by christiangalsterer** [comment]
Hi,

currently this is not supported.

**Comment by ruflin** [comment]
@aboullaite I wonder if the http module in Metricbeat (which is coming from httpbeat) would help you? Or are you missing some features there?

**Comment by aboullaite** [comment]
@ruflin I think that Metricbeat allows you to configure all modules on one file `metricbeat.yml`, but not a directory that contains separated conf for each module (https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-metricbeat.html#enable-modules-config-file), which is the feature I'm looking for :) ?! am I right ?

**Comment by ruflin** [comment]
@aboullaite https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-configuration-reloading.html ?

**Comment by aboullaite** [comment]
Awesome! This is exactly what I was looking for 👍 Thanks (didn't knew about it before ;) )
