### ISSUE TITLE
Got error when compile the code

### ISSUE THREAD

**Issue by stevesui** [christiangalsterer/httpbeat#6]
I ran into the following error after cloning from github.

make
# first make sure we have godep
go get github.com/tools/godep
/Users/stevesui/go_work:/Users/stevesui/go_work/httpbeat/bin/godep go build
make: /Users/stevesui/go_work:/Users/stevesui/go_work/httpbeat/bin/godep: No such file or directory
make: *** [httpbeat] Error 1

Basically, I am not sure when the bin directory will be created during the make process. 

Thanks.

**Comment by stevesui** [comment]
I tried to use go install command and got the following error:
go install
# github.com/christiangalsterer/httpbeat/beat
beat/httpbeat.go:34: b.Events undefined (type *beat.Beat has no field or method Events)

Please advise on how to resolve the issue.

Thanks.

**Comment by jebbenbow** [comment]
Same error here when attempting to build on windows.  

```
# github.com/christiangalsterer/httpbeat/beat
beat\httpbeat.go:34: b.events undefined (type *beat.Beat has no field or method events)
```

**Comment by rickmuca** [comment]
I had the same problem. To solve this quickly, you have to go to the beats library (should be downloaded in <gopath>\src\github.com\elastic\beats) and checkout to v.1.2.0 tag.

**Comment by rkmresh** [comment]
I get following error can some someone help me please?
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: ../Tools/httpbeat-master
godep: [WARNING]:	$GOPATH: ../Tools/httpbeat-master
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
main.go:5:2: cannot find package "github.com/christiangalsterer/httpbeat/beat" in any of:
	/usr/local/go/src/github.com/christiangalsterer/httpbeat/beat (from $GOROOT)
	../Tools/httpbeat-master/Godeps/_workspace/src/github.com/christiangalsterer/httpbeat/beat (from $GOPATH)
	.../Tools/httpbeat-master/src/github.com/christiangalsterer/httpbeat/beat
godep: go exit status 1
make: *** [httpbeat] Error 1

**Comment by christiangalsterer** [comment]
Not sure if this makes a difference but it seems that you are using Go 1.6. I used 1.5 so far make this makes a difference.

Can you also check that your GOPATH env variable is set correctly? I have set it to the parent directory of all my Go projects.

**Comment by ruflin** [comment]
Could it be that this is related to different versions of libbeat used? Golang 1.6 as GOVENDOREXPERIMENT enabled by default and we use it in libbeat.

**Comment by christiangalsterer** [comment]
I think so too.
I will update a new version soon, using Glide for better dependency management/version handling.

**Comment by christiangalsterer** [comment]
Version 1.2.0 now available using glide

**Comment by yuhangOstorage** [comment]
Thanks @christiangalsterer ，
    your work helps me a lot, while I was trying to use the httpbeat. First I install gvm,then I install golang1.4 and golang1.6.3,then glide,then I cd $GOROOT/src and I git clone httpbeat,after I make httpbeat ,these errors appears, can you help me? thanks
main.go:5:2: cannot find package "github.com/christiangalsterer/httpbeat/beat" in any of:
	/home/ubuntu/.gvm/gos/go1.6.3/src/httpbeat/vendor/github.com/christiangalsterer/httpbeat/beat (vendor tree)
	/home/ubuntu/.gvm/gos/go1.6.3/src/vendor/github.com/christiangalsterer/httpbeat/beat
	/home/ubuntu/.gvm/gos/go1.6.3/src/github.com/christiangalsterer/httpbeat/beat (from $GOROOT)
	/home/ubuntu/.gvm/pkgsets/go1.6.3/global/src/github.com/christiangalsterer/httpbeat/beat (from $GOPATH)
make: *** [httpbeat] Error 1

**Comment by christiangalsterer** [comment]
Where is the $GOPATH variable pointing too? It should point to the root of all your go projects.
